### Get

GET http://localhost:3660/kelas


### Post

POST http://localhost:3660/kelas
Content-Type: application/json

{
    "nama": "kelas"
}

### Put

PUT http://localhost:3660/kelas
Content-Type: application/json

{
    "_id": "61fbc2162e13784c71d88bf1",
    "nama": "kelas"
}